# Default values for spring-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  imageName: bhvishal91/docker-mysql-spring-boot-example:latest
  pullPolicy: Always

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

envVars:
  MYSQL_HOST: "mysql-0.mysql"
  MYSQL_DB: "test"
  MYSQL_USER: "sa"
  MYSQL_PASS: ""
