name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker image
      run: docker build . --file Dockerfile --tag bhvishal91/docker-mysql-spring-boot-example:latest
    - name: Push docker image
      run: docker push bhvishal91/docker-mysql-spring-boot-example:latest
