name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USER }}/docker-mysql-spring-boot-example:$GITHUB_ACTION
        docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASS }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/docker-mysql-spring-boot-example:$GITHUB_ACTION

  deploy_mysql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Mysql
      uses: WyriHaximus/github-action-helm3@v1.0.0
      with:
        exec: |
          helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
          helm repo update
          helm upgrade --install --wait mysql incubator/mysqlha \
          --set mysqlha.replicaCount=$MYSQL_REPLICA_COUNT,mysqlha.mysqlUser=$MYSQL_USER,mysqlha.mysqlDatabase=$MYSQL_DB,mysqlha.mysqlPassword=$MYSQL_PASS
        kubeconfig: '${{ secrets.KUBE_CONFIG_DATA }}'
      env:
        MYSQL_REPLICA_COUNT: 2
        MYSQL_USER: sa
        MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
        MYSQL_DB: test
